### ISSUE TITLE
why do you use Elastic Search

### ISSUE THREAD

**Issue by MaryLilian** [cbattlegear/ElasticSearchDataFactory#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Elastic search in your project instead of others like Redis Search or Full text search extension for RDBMS , are there any special features that others dont have it. Can you share me it. I am wondering when I should choose KubeMQ instead of others like Redis Search or Full text search extension

**Comment by cbattlegear** [comment]
Elasticsearch was used in this situation because the end user had a large elasticsearch cluster and needed the data moved into a data lake environment for reporting. No connector or good documentation existed so I built out this.
